- name: Update and Upgrade APT Packages
  hosts: servers
  become: yes  # Ensure sudo privileges

  tasks:
    - name: ✅ Connected to {{ inventory_hostname }} 
      debug:
        msg: "Successfully connected to {{ inventory_hostname }}"

    - name: Update APT Cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages
      apt:
        upgrade: full
      when: ansible_os_family == "Debian"

    - name: Cleanup Unused Packages
      apt:
        autoremove: yes
        autoclean: yes

- name: Update and Upgrade APT Packages
  hosts: servers
  become: yes  # Ensures root privileges
  tasks:
    - name: Display Start Message
      debug:
        msg: "Starting APT update and upgrade process on the servers."

    - name: Update APT Cache
      apt:
        update_cache: yes
        cache_valid_time: 86400  # Cache valid for one day
      register: cache_result  # Register the result of this task

    - name: Show APT Cache Result
      debug:
        var: cache_result

    - name: Upgrade All Packages
      apt:
        upgrade: dist  # Ensures distribution upgrades
      register: upgrade_result

    - name: Display Upgrade Results
      debug:
        msg: "Packages upgraded successfully. Details:\n{{ upgrade_result.stdout }}"

    - name: Cleanup Unused Packages
      apt:
        autoremove: yes
        autoclean: yes

    - name: Display Completion Message
      debug:
        msg: "APT update and upgrade process completed successfully!"

