- name: Verify connection to remote machines
  hosts: servers
  become: yes
  tasks:
    - name: ✅ Connected to {{ inventory_hostname }}
      debug:
        msg: "Successfully connected to {{ inventory_hostname }} - Ready for updates!"


  tasks:
    - name: ✅ Connected to {{ inventory_hostname }}
      debug:
        msg: "Successfully connected to {{ inventory_hostname }} - Updating system now..."

    - name: 🔄 Updating APT Cache on {{ inventory_hostname }}
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: 🚀 Upgrading all packages on {{ inventory_hostname }}
      apt:
        upgrade: full
      when: ansible_os_family == "Debian"

    - name: 🧹 Cleaning up unused packages on {{ inventory_hostname }}
      apt:
        autoremove: yes
        autoclean: yes

    - name: ✅ Update complete on {{ inventory_hostname }}
      debug:
        msg: "Update process completed on {{ inventory_hostname }}"
